services:
  notes_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: ["5432:5432"]
    restart: always
  notes_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  notes_app:
    build:
      context: .
    container_name: Notes
    develop:
      watch:
        - action: rebuild
          path: package.json
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@notes_postgres:5432/postgres
      PORT: 4004
      NODE_ENV: production
    ports:
      - 4004:4004
    depends_on:
      - notes_postgres
